# Generated by Django 3.0.8 on 2020-07-26 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proceedings', '0001_initial'),
        ('conferences', '0001_initial'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameraready',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='submissions.Submission'),
        ),
        migrations.AddField(
            model_name='cameraready',
            name='volume',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conferences.ProceedingVolume'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='submissions.Attachment'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='camera_ready',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proceedings.CameraReady'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='descriptor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conferences.ArtifactDescriptor'),
        ),
        migrations.AlterUniqueTogether(
            name='cameraready',
            unique_together={('submission', 'proc_type')},
        ),
    ]
