# Generated by Django 3.0.8 on 2020-07-26 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_html', models.TextField()),
                ('text_plain', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(max_length=1024)),
                ('text_plain', models.TextField()),
                ('text_html', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=1024)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('assign_status_review', 'Assign status REVIEW to the paper'), ('assign_status_submit', 'Assign status SUBMIT to the paper'), ('assign_status_accept', 'Assign status ACCEPT to the paper'), ('assign_status_reject', 'Assign status REJECT to the paper'), ('assign_status_inprint', 'Assign status IN-PRINT to the paper'), ('assign_status_publish', 'Assign status PUBLISHED to the paper')], max_length=64)),
                ('subject', models.CharField(blank=True, max_length=1024)),
                ('is_active', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('user', 'Message to users'), ('submission', 'Message to submissions')], max_length=64)),
                ('body', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionMessage',
            fields=[
                ('group_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chair_mail.GroupMessage')),
            ],
            bases=('chair_mail.groupmessage',),
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('group_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chair_mail.GroupMessage')),
            ],
            bases=('chair_mail.groupmessage',),
        ),
    ]
