# Generated by Django 3.0.8 on 2020-07-26 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conferences', '0002_auto_20200725_2215'),
        ('review', '0002_auto_20200725_2215'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewdecisiontype',
            name='allowed_proceedings',
            field=models.ManyToManyField(related_name='decision_types', to='conferences.ProceedingType'),
        ),
        migrations.AddField(
            model_name='reviewdecisiontype',
            name='conference',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='conferences.Conference'),
        ),
        migrations.AddField(
            model_name='reviewdecision',
            name='decision_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='review.ReviewDecisionType'),
        ),
        migrations.AddField(
            model_name='reviewdecision',
            name='stage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='review.ReviewStage'),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='review.Reviewer'),
        ),
        migrations.AddField(
            model_name='review',
            name='stage',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='review.ReviewStage'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewdecisiontype',
            unique_together={('conference', 'decision', 'description')},
        ),
    ]
